alias ll='ls -lah'
alias poweroff='systemctl poweroff'
alias reboot='systemctl reboot'
alias hdmi-on='xrandr --setprovideroutputsource 1 0'
alias hdmi-conf='xrandr --output eDP-1 --mode 1920x1080 --scale 1x1 --output HDMI-1-1 --same-as eDP-1 --mode 1920x1080'
